FROM python:3.9.8-slim

WORKDIR /app

# Install Node.js 14.x
RUN apt update \
    && apt install -y curl \
    && curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt install -y nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY . .

EXPOSE 3000
